<a href="https://colab.research.google.com/github/Bharatgaur/Trading/blob/main/TRADE_PROBABILITIES_BASE_FILE_Version_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [86]:
BASE_CAPITAL = 25000
PERCENTAGE = 0.30  # 30% of capital
LOT_SIZE = 15  # 15 units per trade
TARGET_PCT = 40
STOPLOSS_PCT = 60

# **ENTRY PRICE**

In [87]:
import pandas as pd
import random

# Generate trade numbers from "TRADE 0001" to "TRADE 1000"
trade_numbers = [f"TRADE {str(i).zfill(4)}" for i in range(1, 1001)]

# Create a dictionary to hold data for all columns
data = {
    "TRADE NO": trade_numbers  # First column: Trade numbers
}

# Generate 1000 columns with random numbers between 100 and 500
for col_num in range(1, 1001):
    column_name = f"COLUMN_{col_num}"
    data[column_name] = [random.randint(300, 450) for _ in range(1000)]

# Create the DataFrame with 1001 columns
df = pd.DataFrame(data)

# Save the DataFrame to a single CSV file
df.to_csv('trade_entry_1001_columns.csv', index=False)

# Print confirmation message
print("CSV file 'trade_entry_1001_columns.csv' has been created.")

CSV file 'trade_entry_1001_columns.csv' has been created.

In [88]:
pd.read_csv('trade_entry_1001_columns.csv')

,TRADE NO,COLUMN_1,COLUMN_2,COLUMN_3,COLUMN_4,COLUMN_5,COLUMN_6,COLUMN_7,COLUMN_8,COLUMN_9,...,COLUMN_991,COLUMN_992,COLUMN_993,COLUMN_994,COLUMN_995,COLUMN_996,COLUMN_997,COLUMN_998,COLUMN_999,COLUMN_1000
0,TRADE 0001,447,320,446,423,393,315,414,449,351,...,404,352,311,350,363,433,374,357,420,309
1,TRADE 0002,435,364,440,396,439,355,404,340,423,...,382,353,388,436,319,393,336,348,446,354
2,TRADE 0003,445,335,433,394,365,388,397,349,354,...,332,338,411,409,401,433,307,316,367,421
3,TRADE 0004,356,440,363,312,440,300,412,366,367,...,338,306,394,342,400,450,324,325,449,425
4,TRADE 0005,329,371,367,337,349,426,314,411,439,...,340,371,388,437,436,326,376,448,362,374
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,TRADE 0996,342,432,301,326,400,401,372,443,427,...,300,433,355,353,349,325,442,417,403,345
996,TRADE 0997,414,408,316,377,364,304,310,418,340,...,312,323,393,396,361,358,434,331,403,437
997,TRADE 0998,309,447,417,333,435,321,381,392,426,...,357,423,396,383,371,332,397,343,352,401
998,TRADE 0999,433,450,314,365,388,354,393,337,365,...,437,346,348,339,324,388,406,314,440,348
999,TRADE 1000,364,420,400,325,302,427,387,318,303,...,369,446,367,336,441,367,307,301,342,387

# **RANDOM TARGET AND STOPLOSS**

**40 % TARGET 60 % STOPLOSS**

**RISK:REWARD 1:2.5**

In [89]:
import pandas as pd
import random

# Generate trade numbers from "TRADE 0001" to "TRADE 1000"
trade_numbers = [f"TRADE {str(i).zfill(4)}" for i in range(1, 1001)]

# Create a dictionary to hold data for all columns
data = {
    "TRADE NO": trade_numbers  # First column: Trade numbers
}

# Function to randomly assign "TARGET" (40%) or "STOPLOSS" (60%)
def assign_target_or_stoploss():
    return random.choices(["TARGET", "STOPLOSS"], weights=[TARGET_PCT, STOPLOSS_PCT], k=1)[0]

# Generate 1000 columns with "TARGET" or "STOPLOSS"
for col_num in range(1, 1001):
    column_name = f"COLUMN_{col_num}"
    data[column_name] = [assign_target_or_stoploss() for _ in range(1000)]

# Create the DataFrame with 1001 columns
df = pd.DataFrame(data)

# Save the DataFrame to a single CSV file
df.to_csv('trade_target_stoploss_1001_columns.csv', index=False)

# Print confirmation message
print("CSV file 'trade_target_stoploss_1001_columns.csv' has been created.")

CSV file 'trade_target_stoploss_1001_columns.csv' has been created.

In [90]:
pd.read_csv('trade_target_stoploss_1001_columns.csv')

,TRADE NO,COLUMN_1,COLUMN_2,COLUMN_3,COLUMN_4,COLUMN_5,COLUMN_6,COLUMN_7,COLUMN_8,COLUMN_9,...,COLUMN_991,COLUMN_992,COLUMN_993,COLUMN_994,COLUMN_995,COLUMN_996,COLUMN_997,COLUMN_998,COLUMN_999,COLUMN_1000
0,TRADE 0001,TARGET,STOPLOSS,TARGET,STOPLOSS,STOPLOSS,STOPLOSS,TARGET,STOPLOSS,TARGET,...,STOPLOSS,STOPLOSS,TARGET,TARGET,STOPLOSS,STOPLOSS,STOPLOSS,STOPLOSS,STOPLOSS,STOPLOSS
1,TRADE 0002,TARGET,TARGET,STOPLOSS,STOPLOSS,STOPLOSS,STOPLOSS,STOPLOSS,TARGET,STOPLOSS,...,TARGET,STOPLOSS,STOPLOSS,STOPLOSS,STOPLOSS,STOPLOSS,STOPLOSS,STOPLOSS,STOPLOSS,TARGET
2,TRADE 0003,TARGET,TARGET,STOPLOSS,STOPLOSS,STOPLOSS,STOPLOSS,STOPLOSS,TARGET,TARGET,...,TARGET,STOPLOSS,TARGET,TARGET,STOPLOSS,STOPLOSS,STOPLOSS,STOPLOSS,STOPLOSS,STOPLOSS
3,TRADE 0004,TARGET,TARGET,TARGET,STOPLOSS,TARGET,STOPLOSS,STOPLOSS,STOPLOSS,TARGET,...,TARGET,STOPLOSS,STOPLOSS,STOPLOSS,STOPLOSS,STOPLOSS,STOPLOSS,STOPLOSS,TARGET,TARGET
4,TRADE 0005,STOPLOSS,STOPLOSS,TARGET,STOPLOSS,STOPLOSS,STOPLOSS,STOPLOSS,TARGET,TARGET,...,TARGET,STOPLOSS,STOPLOSS,STOPLOSS,TARGET,STOPLOSS,STOPLOSS,TARGET,TARGET,STOPLOSS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,TRADE 0996,STOPLOSS,TARGET,STOPLOSS,TARGET,TARGET,TARGET,STOPLOSS,STOPLOSS,TARGET,...,TARGET,STOPLOSS,TARGET,STOPLOSS,TARGET,TARGET,STOPLOSS,TARGET,STOPLOSS,STOPLOSS
996,TRADE 0997,STOPLOSS,STOPLOSS,STOPLOSS,STOPLOSS,STOPLOSS,STOPLOSS,STOPLOSS,TARGET,TARGET,...,TARGET,STOPLOSS,STOPLOSS,STOPLOSS,TARGET,TARGET,STOPLOSS,TARGET,STOPLOSS,TARGET
997,TRADE 0998,STOPLOSS,STOPLOSS,STOPLOSS,STOPLOSS,TARGET,STOPLOSS,STOPLOSS,STOPLOSS,STOPLOSS,...,TARGET,STOPLOSS,TARGET,TARGET,TARGET,TARGET,STOPLOSS,TARGET,TARGET,STOPLOSS
998,TRADE 0999,TARGET,STOPLOSS,TARGET,STOPLOSS,STOPLOSS,STOPLOSS,TARGET,STOPLOSS,TARGET,...,STOPLOSS,STOPLOSS,STOPLOSS,STOPLOSS,TARGET,STOPLOSS,STOPLOSS,TARGET,TARGET,TARGET
999,TRADE 1000,STOPLOSS,STOPLOSS,STOPLOSS,TARGET,STOPLOSS,STOPLOSS,STOPLOSS,STOPLOSS,STOPLOSS,...,TARGET,STOPLOSS,STOPLOSS,TARGET,TARGET,STOPLOSS,TARGET,STOPLOSS,TARGET,TARGET

In [91]:
import pandas as pd

# Load the CSV file
df = pd.read_csv('trade_target_stoploss_1001_columns.csv')

# Count the frequency of "TARGET" and "STOPLOSS" in COLUMN_1
frequency = df['COLUMN_343'].value_counts()/10

# Print the results
print(frequency)

COLUMN_343
STOPLOSS    63.2
TARGET      36.8
Name: count, dtype: float64

# **PnL**

In [92]:
import pandas as pd

# Load the two CSV files
entry_df = pd.read_csv('trade_entry_1001_columns.csv')
target_stoploss_df = pd.read_csv('trade_target_stoploss_1001_columns.csv')

# Base capital to be added to the first row of each column
BASE_CAPITAL = 25000

# Create an empty dictionary to hold the PnL data
pnl_data = {
    "TRADE NO": entry_df["TRADE NO"]  # Retain the "TRADE NO" column
}

# Iterate over each column (excluding "TRADE NO") to apply the PnL logic
for column in entry_df.columns[1:]:
    # Calculate PnL values for the column
    pnl_values = target_stoploss_df[column].apply(lambda x: (50 if x == "TARGET" else -20) * LOT_SIZE)

    # Create a Series with the base capital and concatenate it with PnL values
    base_series = pd.Series([BASE_CAPITAL])
    cumulative_pnl = pd.concat([base_series, pnl_values], ignore_index=True).cumsum()

    # Store the cumulative PnL in the dictionary (excluding the initial capital row)
    pnl_data[column] = cumulative_pnl.iloc[1:].values

# Create a DataFrame from the PnL data
pnl_df = pd.DataFrame(pnl_data)

# Save the modified PnL DataFrame to a new CSV file
pnl_df.to_csv('trade_pnl_1001_columns.csv', index=False)

# Print confirmation message
print("CSV file 'trade_pnl_1001_columns.csv' has been created with cumulative PnL and base capital added.")

CSV file 'trade_pnl_1001_columns.csv' has been created with cumulative PnL and base capital added.

In [93]:
pd.read_csv('trade_pnl_1001_columns.csv')

,TRADE NO,COLUMN_1,COLUMN_2,COLUMN_3,COLUMN_4,COLUMN_5,COLUMN_6,COLUMN_7,COLUMN_8,COLUMN_9,...,COLUMN_991,COLUMN_992,COLUMN_993,COLUMN_994,COLUMN_995,COLUMN_996,COLUMN_997,COLUMN_998,COLUMN_999,COLUMN_1000
0,TRADE 0001,25750,24700,25750,24700,24700,24700,25750,24700,25750,...,24700,24700,25750,25750,24700,24700,24700,24700,24700,24700
1,TRADE 0002,26500,25450,25450,24400,24400,24400,25450,25450,25450,...,25450,24400,25450,25450,24400,24400,24400,24400,24400,25450
2,TRADE 0003,27250,26200,25150,24100,24100,24100,25150,26200,26200,...,26200,24100,26200,26200,24100,24100,24100,24100,24100,25150
3,TRADE 0004,28000,26950,25900,23800,24850,23800,24850,25900,26950,...,26950,23800,25900,25900,23800,23800,23800,23800,24850,25900
4,TRADE 0005,27700,26650,26650,23500,24550,23500,24550,26650,27700,...,27700,23500,25600,25600,24550,23500,23500,24550,25600,25600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,TRADE 0996,138850,124150,134650,127300,145150,157750,143050,170350,137800,...,140950,116800,156700,134650,149350,124150,148300,147250,121000,152500
996,TRADE 0997,138550,123850,134350,127000,144850,157450,142750,171100,138550,...,141700,116500,156400,134350,150100,124900,148000,148000,120700,153250
997,TRADE 0998,138250,123550,134050,126700,145600,157150,142450,170800,138250,...,142450,116200,157150,135100,150850,125650,147700,148750,121450,152950
998,TRADE 0999,139000,123250,134800,126400,145300,156850,143200,170500,139000,...,142150,115900,156850,134800,151600,125350,147400,149500,122200,153700
999,TRADE 1000,138700,122950,134500,127150,145000,156550,142900,170200,138700,...,142900,115600,156550,135550,152350,125050,148150,149200,122950,154450

# **QUANTITY CALCULATION**

In [94]:
import pandas as pd

# Load entry and target/stoploss data
entry_df = pd.read_csv('trade_entry_1001_columns.csv')
target_stoploss_df = pd.read_csv('trade_target_stoploss_1001_columns.csv')

# Create a dictionary to store the final PnL and QTY data
final_data = {"TRADE NO": entry_df["TRADE NO"]}  # Retain "TRADE NO"

# Iterate over each column (excluding "TRADE NO") to calculate cumulative PnL and QTY
for column in entry_df.columns[1:]:
    cumulative_capital = BASE_CAPITAL  # Initialize with BASE_CAPITAL
    pnl_column = []  # Store cumulative PnL values
    qty_column = []  # Store QTY values

    # Loop over each row to calculate QTY and update cumulative PnL
    for i in range(len(entry_df)):
        # Calculate QTY for the current row
        entry_price = entry_df[column].iloc[i]
        capital_allocation = cumulative_capital * PERCENTAGE
        qty = int(capital_allocation / (entry_price * LOT_SIZE)) if entry_price > 0 else 0
        qty_column.append(qty)

        # Calculate PnL for the current trade based on the target/stoploss
        pnl_value = (50 if target_stoploss_df[column].iloc[i] == "TARGET" else -20) * LOT_SIZE
        trade_pnl = qty * pnl_value  # Multiply QTY with PnL per trade

        # Update cumulative capital for the next row
        cumulative_capital += trade_pnl
        pnl_column.append(cumulative_capital)

    # Store the PnL and QTY values in the final data dictionary
    final_data[f"{column}_QTY"] = qty_column
    final_data[f"{column}_CUM_PNL"] = pnl_column

# Create a DataFrame from the final data
final_df = pd.DataFrame(final_data)

# Save the DataFrame to a single CSV file
final_df.to_csv('final_PnL.csv', index=False)

# Print confirmation message
print("CSV file 'final_PnL.csv' has been created with QTY and cumulative PnL.")

CSV file 'final_PnL.csv' has been created with QTY and cumulative PnL.

In [95]:
pd.read_csv('final_PnL.csv')

,TRADE NO,COLUMN_1_QTY,COLUMN_1_CUM_PNL,COLUMN_2_QTY,COLUMN_2_CUM_PNL,COLUMN_3_QTY,COLUMN_3_CUM_PNL,COLUMN_4_QTY,COLUMN_4_CUM_PNL,COLUMN_5_QTY,...,COLUMN_996_QTY,COLUMN_996_CUM_PNL,COLUMN_997_QTY,COLUMN_997_CUM_PNL,COLUMN_998_QTY,COLUMN_998_CUM_PNL,COLUMN_999_QTY,COLUMN_999_CUM_PNL,COLUMN_1000_QTY,COLUMN_1000_CUM_PNL
0,TRADE 0001,1,25750,1,24700,1,25750,1,24700,1,...,1,24700,1,24700,1,24700,1,24700,1,24700
1,TRADE 0002,1,26500,1,25450,1,25450,1,24400,1,...,1,24400,1,24400,1,24400,1,24400,1,25450
2,TRADE 0003,1,27250,1,26200,1,25150,1,24100,1,...,1,24100,1,24100,1,24100,1,24100,1,25150
3,TRADE 0004,1,28000,1,26950,1,25900,1,23800,1,...,1,23800,1,23800,1,23800,1,24850,1,25900
4,TRADE 0005,1,27700,1,26650,1,26650,1,23500,1,...,1,23500,1,23500,1,24550,1,25600,1,25600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,TRADE 0996,278,4685500,84,1888750,217,3205000,157,2689900,366,...,137,2342800,354,7724350,429,9270250,103,2056000,644,10925500
996,TRADE 0997,226,4617700,92,1861150,202,3144400,142,2647300,417,...,130,2440300,355,7617850,560,9690250,102,2025400,500,11300500
997,TRADE 0998,298,4528300,83,1836250,150,3099400,158,2599900,343,...,147,2550550,383,7502950,565,10114000,115,2111650,563,11131600
998,TRADE 0999,209,4685050,81,1811950,197,3247150,142,2557300,398,...,131,2511250,369,7392250,644,10597000,95,2182900,639,11610850
999,TRADE 1000,257,4607950,86,1786150,162,3198550,157,2675050,504,...,136,2470450,481,7753000,704,10385800,127,2278150,600,12060850

In [96]:
import pandas as pd

# Load the final_PnL.csv file
final_df = pd.read_csv('final_PnL.csv')

# Extract all columns containing QTY (columns ending with "_QTY")
qty_columns = [col for col in final_df.columns if col.endswith("_QTY")]

# Find the maximum QTY value across all QTY columns
max_qty = final_df[qty_columns].max().max()

print(f"The maximum QTY value is: {max_qty}")

The maximum QTY value is: 5993

In [97]:
import pandas as pd

# Load the final_PnL.csv file
final_df = pd.read_csv('final_PnL.csv')

# Extract all columns containing cumulative PnL (columns ending with "_CUM_PNL")
pnl_columns = [col for col in final_df.columns if col.endswith("_CUM_PNL")]

# Find the maximum PnL value across all PnL columns
max_pnl = final_df[pnl_columns].max().max()

print(f"The maximum PnL value is: {max_pnl}")

The maximum PnL value is: 96417700

In [100]:
import pandas as pd

# Load entry and target/stoploss data
entry_df = pd.read_csv('trade_entry_1001_columns.csv')
target_stoploss_df = pd.read_csv('trade_target_stoploss_1001_columns.csv')

# Create a dictionary to store the final PnL and QTY data
final_data = {"TRADE NO": entry_df["TRADE NO"]}  # Retain "TRADE NO"

# Iterate over each column (excluding "TRADE NO") to calculate cumulative PnL and QTY
for column in entry_df.columns[1:]:
    cumulative_capital = BASE_CAPITAL  # Initialize with BASE_CAPITAL
    pnl_column = []  # Store cumulative PnL values
    qty_column = []  # Store QTY values

    # Loop over each row to calculate QTY and update cumulative PnL
    for i in range(len(entry_df)):
        # Extract entry price and target/stoploss information
        entry_price = entry_df[column].iloc[i]
        target_or_stoploss = target_stoploss_df[column].iloc[i]

        # Calculate QTY for the current row
        capital_allocation = cumulative_capital * PERCENTAGE
        qty = int(capital_allocation / (entry_price * LOT_SIZE)) if entry_price > 0 else 0
        qty_column.append(qty)

        # Calculate Buy and Sell Values
        buy_value = entry_price * LOT_SIZE * qty
        sell_value = (entry_price + (50 if target_or_stoploss == "TARGET" else -20)) * LOT_SIZE * qty

        # Calculate Net PnL
        net_pnl = sell_value - buy_value

        # Calculate Transaction Charges
        brokerage = 0.01
        transaction_charges_buy = 0.03503 / 100 * buy_value
        transaction_charges_sell = 0.03503 / 100 * sell_value
        stt = 0.1 / 100 * sell_value
        ipft = 0.0005 / 100 * (buy_value + sell_value)
        stamp_duty = 0.003 / 100 * (buy_value + sell_value)
        sebi_charges = 0.0001 / 100 * (buy_value + sell_value)

        # Total Charges
        total_charges = (brokerage +
                         transaction_charges_buy +
                         transaction_charges_sell +
                         stt +
                         ipft +
                         stamp_duty +
                         sebi_charges)

        # GST Calculation
        gst = 0.18 * (brokerage +
                      transaction_charges_buy +
                      transaction_charges_sell +
                      stt +
                      ipft +
                      stamp_duty +
                      sebi_charges)

        # Final PnL Calculation
        if net_pnl > 0:  # Profit scenario
            final_pnl = net_pnl - (total_charges + gst)
        else:  # Loss scenario
            final_pnl = net_pnl + (-total_charges - gst)

        # Update cumulative capital for the next row
        cumulative_capital += final_pnl
        pnl_column.append(cumulative_capital)

    # Store the QTY values as integers and cumulative PnL as floats in the final data dictionary
    final_data[f"{column}_QTY"] = qty_column
    final_data[f"{column}_CUM_PNL"] = pnl_column

# Create a DataFrame from the final data
final_df = pd.DataFrame(final_data)

# Format the cumulative PnL column to 2 decimal places
for column in entry_df.columns[1:]:
    final_df[f"{column}_CUM_PNL"] = final_df[f"{column}_CUM_PNL"].apply(lambda x: f"{x:.2f}")

# Save the DataFrame to a single CSV file
final_df.to_csv('final_PnL.csv', index=False)

# Print confirmation message
print("CSV file 'final_PnL.csv' has been created with QTY as integers and cumulative PnL formatted to two decimal places.")

CSV file 'final_PnL.csv' has been created with QTY as integers and cumulative PnL formatted to two decimal places.

In [101]:
pd.read_csv('final_PnL.csv')

,TRADE NO,COLUMN_1_QTY,COLUMN_1_CUM_PNL,COLUMN_2_QTY,COLUMN_2_CUM_PNL,COLUMN_3_QTY,COLUMN_3_CUM_PNL,COLUMN_4_QTY,COLUMN_4_CUM_PNL,COLUMN_5_QTY,...,COLUMN_996_QTY,COLUMN_996_CUM_PNL,COLUMN_997_QTY,COLUMN_997_CUM_PNL,COLUMN_998_QTY,COLUMN_998_CUM_PNL,COLUMN_999_QTY,COLUMN_999_CUM_PNL,COLUMN_1000_QTY,COLUMN_1000_CUM_PNL
0,TRADE 0001,1,25734.74,1,24690.44,1,25734.77,1,24687.21,1,...,1,24686.89,1,24688.74,1,24689.28,1,24687.30,1,24690.78
1,TRADE 0002,1,26469.85,1,25427.78,1,25421.44,1,24375.26,1,...,1,24375.04,1,24378.68,1,24378.84,1,24373.79,1,25428.44
2,TRADE 0003,1,27204.65,1,26166.03,1,25108.34,1,24063.38,1,...,1,24061.94,1,24069.53,1,24069.40,1,24062.75,1,25115.71
3,TRADE 0004,1,27942.24,1,26900.99,1,25845.71,1,23754.07,1,...,1,23748.30,1,23759.84,1,23759.69,1,24797.43,1,25851.14
4,TRADE 0005,1,27632.40,1,26589.83,1,26582.95,1,23443.97,1,...,1,23438.55,1,23448.52,1,24494.39,1,25534.83,1,25539.88
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,TRADE 0996,157,2651489.36,45,1024039.83,121,1788820.20,75,1291584.74,219,...,80,1364165.30,171,3734009.27,214,4636212.96,56,1130587.68,341,5788948.72
996,TRADE 0997,128,2611489.54,50,1008424.30,113,1753855.31,68,1270413.77,249,...,76,1420218.39,172,3680151.59,280,4842961.59,56,1113107.08,264,5983005.14
997,TRADE 0998,169,2559234.03,45,994315.27,84,1727597.52,76,1246857.02,205,...,85,1482978.69,185,3622438.03,282,5051080.82,63,1159584.00,298,5890002.12
998,TRADE 0999,118,2645986.17,44,980515.62,110,1808878.85,68,1225711.65,237,...,76,1459290.79,178,3566857.96,321,5288274.57,52,1197802.33,338,6139396.97
999,TRADE 1000,145,2600901.35,46,966132.02,90,1780793.51,75,1281104.85,300,...,79,1434719.89,232,3738338.66,351,5179832.01,70,1249465.32,317,6372908.98

In [102]:
import pandas as pd

# Load the final_PnL.csv file
final_df = pd.read_csv('final_PnL.csv')

# Extract all columns containing QTY (columns ending with "_QTY")
qty_columns = [col for col in final_df.columns if col.endswith("_QTY")]

# Find the maximum QTY value across all QTY columns
max_qty = final_df[qty_columns].max().max()

print(f"The maximum QTY value is: {max_qty}")

The maximum QTY value is: 3346

In [103]:
import pandas as pd

# Load the final_PnL.csv file
final_df = pd.read_csv('final_PnL.csv')

# Extract all columns containing cumulative PnL (columns ending with "_CUM_PNL")
pnl_columns = [col for col in final_df.columns if col.endswith("_CUM_PNL")]

# Find the maximum PnL value across all PnL columns
max_pnl = final_df[pnl_columns].max().max()

print(f"The maximum PnL value is: {max_pnl}")

The maximum PnL value is: 53862638.03